table Acumulado
	lineageTag: e8368ac9-7f59-582c-8e61-3aa3368faf87

	column Concepto
		dataType: string
		lineageTag: 133de7b3-a51c-5ebb-8f97-416540e70c97
		summarizeBy: none
		sourceColumn: Concepto
		sortByColumn: Orden

		annotation SummarizationSetBy = User

	column Orden
		dataType: int64
		isHidden
		lineageTag: 960a2e59-c359-5d10-b7ea-a46143c526ae
		summarizeBy: none
		sourceColumn: Orden

		annotation SummarizationSetBy = User

	partition Acumulado = m
		mode: import
		source =
				let
				    Fuente = #table({"Concepto", "Orden"}, {{"Ingresos", 1}, {"EBITDA ajustado", 2}, {"Flujo operativo", 3}, {"Capex", 4}}),
				    Tipos = Table.TransformColumnTypes(Fuente, {{"Concepto", type text}, {"Orden", Int64.Type}})
				in
				    Tipos

